### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by contortionist** [hensing/python_talks#1]
clearly you mean: THANK YOU FUR YOUR ATTENTION
change
https://github.com/hensing/python_talks/blob/master/2013_numpy_talk/files/Thank-you--for-your-attention_.jpg
to
https://github.com/hensing/python_talks/blob/master/2013_numpy_talk/files/Thank-you--fur-your-attention_.jpg

**Comment by hensing** [comment]
argument too fluffy - issue closed :3
